name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          lerna bootstrap
          lerna run test
          lerna run lint
