name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          npm i -g npm@6.14.17 --registry=https://registry.npmjs.org
          npm -v
          npm ci --legacy-peer-deps
          npm run test
          npm run lint
